import Head from "next/head";
import { useRouter } from "next/router";
import ScrollSnap from "../src/components/units/landingPage/landingPage.container";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  console.log(router);
  return (
    <>
      <Head>
        <title>Yeji's App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScrollSnap />
    </>
  );
}
